### ISSUE TITLE
NICK required

### ISSUE THREAD

**Issue by EchtkPvL** [3ventic/raw-twchat#1]
According to [dev.twitch.tv/docs/irc/guide](https://dev.twitch.tv/docs/irc/guide#connecting-to-twitch-irc) `NICK <user>` is now required.

To fix this you can type this by yourself or add the following code:

```go
        nick := os.Getenv("TW_NICK")
        if nick == "" {
                log.Println("TW_NICK environment variable missing")
                os.Exit(1)
        }

[...]

        conn.Write([]byte(fmt.Sprintf("NICK %s\r\n", nick)))
        log.Printf("< NICK %s\n", nick)
```

**Comment by 3ventic** [comment]
You're expected to type it in yourself. PASS is only handled so it's not visible in the output without having to code in a separate password input. The name does not have to match the token: the token name is used.
